const express = require('express')
const auth = require('../middleware/tokenVer')
const cors = require('cors')
const bodyParser = require('body-parser')
module.exports = function (app) {
    app.use(cors())
    app.use(express.static('public'))
    app.use(express.json())
    app.use(express.static('public'))
    app.use(bodyParser.urlencoded({ extended: false }))
    app.use(bodyParser.json())
    app.use('/api/user' , require('../router/users'))
    app.use('/api/user' , require('../router/users'))
    app.use('/api/auth/user' , require('../router/auth'))
    app.use(auth)
    app.use('/api/post/image' , require('../router/postImage'))
    app.use('/api/post/image' , require('../router/postImage'))
    app.use('/api/post/image' , require('../router/postImage'))
}